### PR TITLE
Decorate the components before they are rendered

### PR DESCRIPTION
**Pull request by chalbert**
This is useful, among other things, to allow usage of a style library like styled-components or jss.

With styled-components, I do:

```
setConfiguration({
    componentDecorator: (Component) => {
      const StyleComponent = styled(Component)`
        ${({ gridStyles }) => gridStyles}
      `;
  
      const DecoratedComponent = ({ style, ...props }) => <StyleComponent gridStyles={style} {...props} />;
  
      DecoratedComponent.propTypes = {
        style: PropTypes.object,
      };
  
      return DecoratedComponent;
    },
  });
```

### CODE REVIEW

**Comment by zetoke** [comment]
This is looking good and really adds a lot if interop possibilities.

**Comment by gerbenmeyer** [comment]
I don't really understand what this is doing. `this.decoratedComponent = componentDecorator(component);` seems to do nothing when `componentDecorator: Component => Component,` ...

**Comment by chalbert** [comment]
@gerbenmeyer Correct, the `componentDecorator` is opt-in and transparent if not used. Unless a decorator has been configured using `setConfiguration({ componentDecorator })` (like in the example above) it has no effect.

**Comment by gerbenmeyer** [comment]
Maybe you could also apply this pattern then to `Visible` and `Hidden` helpers, and add some documentation on how to use this? Would make it a lot clearer 😃

**Comment by chalbert** [comment]
Thanks, its sounds good. It'll apply to `visible` and `hidden` and improve the docs and come back to you.

**Comment by CesarBMartinez** [comment]
Hi @chalbert and @gerbenmeyer any news about this PR?

**Comment by chalbert** [comment]
Sorry I didn't come back to you. In the end, I was able to achieve what I wanted without adding any new feature. Instead of adding `componentDecorator`, I've wrapped the grid components in my project in a HOC that uses the `component`  prop.

In consequence, I'm closing this PR. I'm sharing my HOC as an example for anybody interested in achieving something similar.

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

export default (displayName) => (WrappedComponent) => {  
  const StyledComponent = styled.div.withConfig({ displayName })`
    ${({ style }) => style}
  `;

  const DecoratedComponentPropTypes = {
    as: PropTypes.elementType,
    component: PropTypes.elementType,
    style: PropTypes.object,
  };

  class DecoratedComponent extends React.PureComponent {
    constructor(props) {
      super(props);
      const { as, component, style: parentStyle } = props;
      const FilteredComponent = ({ style, as: childAs, ...otherProps }) => (
        React.createElement(as || component || 'div', otherProps)
      );

      const DecoratedComponentImpl = ({ style, as: childAs, ...otherProps }) => (
        <StyledComponent 
          as={FilteredComponent} 
          {...otherProps} 
          style={{ ...style, ...parentStyle }} 
        />
      );

      this.decoratedComponent = DecoratedComponentImpl;
    }

    render() {
      const { as, component, ...props } = this.props;
      return React.createElement(WrappedComponent, { component: this.decoratedComponent, ...props });
    }
  }

  DecoratedComponent.propTypes = DecoratedComponentPropTypes;

  return DecoratedComponent;
};
```
And than use it like this:

```jsx
import Col from 'react-grid-system/src/grid/Col';
export default decorateGridComponent('Col')(Col);
```

I'm personally wrapping `Col`, `Row` and `Container`. This example is specific to using `styled-components`, but the pattern could be adapted to other uses. Note two things: First, I expose a `as` prop in additional to `component` as it is a more common standard in my project (and many popular libraries). Second, I do extra work to allow overriding the styles, which is normally impossible.

**Pull request closed without merging**
